### ISSUE TITLE
Error .env

### ISSUE THREAD

**Issue by Butonix** [joincomet/comet#13]
Hello. I tried to install your project, created a file .env in the root directory, returns an error on startup
ACCESS_TOKEN_SECRET environment variable missing. Shutting down.

**Comment by danbeneventano** [comment]
Hi, the project is still undergoing heavy development and the installation instructions are outdated, I'd recommend waiting until we release a beta, at which point the instructions will be updated and the project will be more stable.

If you still want to try to run it, you need to run the script with the environment variables prepended. Currently the .env file is not being read.

**Comment by Butonix** [comment]
> Hi, the project is still undergoing heavy development and the installation instructions are outdated, I'd recommend waiting until we release a beta, at which point the instructions will be updated and the project will be more stable.
> 
> If you still want to try to run it, you need to run the script with the environment variables prepended. Currently the .env file is not being read.

Now error Variable "$name" of required type "String!" was not provided.

**Comment by danbeneventano** [comment]
Thanks, fixed that. There's not much you can do on a newly created account right now, but if you log in with "admin@joincomet.app" and "password" you will have access to everything (currently it is populated with random fake data). The project is still very buggy and incomplete, we are aiming to launch the beta in mid-May (which will be version 0.1.0).

**Comment by Butonix** [comment]
> Thanks, fixed that. There's not much you can do on a newly created account right now, but if you log in with "[admin@joincomet.app](mailto:admin@joincomet.app)" and "password" you will have access to everything (currently it is populated with random fake data). The project is still very buggy and incomplete, we are aiming to launch the beta in mid-May (which will be version 0.1.0).

Hi!
Create Planet
`Missing required key 'Bucket' in params`
